name: Deploy to GitHub Pages
on:
  push:	
    branches:	
      - main

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Deploy
      - uses: s0/git-publish-subdir-action@develop
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
